# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/picasso/extract-files.sh - DO NOT EDIT


# All the blobs necessary for picasso
PRODUCT_COPY_FILES += \
    vendor/acer/picasso/proprietary/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/acer/picasso/proprietary/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/acer/picasso/proprietary/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/acer/picasso/proprietary/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/acer/picasso/proprietary/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/acer/picasso/proprietary/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/acer/picasso/proprietary/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/acer/picasso/proprietary/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/acer/picasso/proprietary/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/acer/picasso/proprietary/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/acer/picasso/proprietary/libnvddk_aes_user.so:system/lib/libnvddk_aes_user.so \
    vendor/acer/picasso/proprietary/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
    vendor/acer/picasso/proprietary/libnvddk_vmr.so:system/lib/libnvddk_vmr.so \
    vendor/acer/picasso/proprietary/libnvdispatch_helper.so:system/lib/libnvdispatch_helper.so \
    vendor/acer/picasso/proprietary/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/acer/picasso/proprietary/libnvec.so:system/lib/libnvec.so \
    vendor/acer/picasso/proprietary/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
    vendor/acer/picasso/proprietary/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/acer/picasso/proprietary/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
    vendor/acer/picasso/proprietary/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/acer/picasso/proprietary/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/acer/picasso/proprietary/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/acer/picasso/proprietary/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/acer/picasso/proprietary/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/acer/picasso/proprietary/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
    vendor/acer/picasso/proprietary/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/acer/picasso/proprietary/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/acer/picasso/proprietary/libnvmm.so:system/lib/libnvmm.so \
    vendor/acer/picasso/proprietary/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
    vendor/acer/picasso/proprietary/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/acer/picasso/proprietary/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/acer/picasso/proprietary/libnvmm_videorenderer.so:system/lib/libnvmm_videorenderer.so \
    vendor/acer/picasso/proprietary/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/acer/picasso/proprietary/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/acer/picasso/proprietary/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/acer/picasso/proprietary/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/acer/picasso/proprietary/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/acer/picasso/proprietary/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/acer/picasso/proprietary/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/acer/picasso/proprietary/libnvomx.so:system/lib/libnvomx.so \
    vendor/acer/picasso/proprietary/libnvos.so:system/lib/libnvos.so \
    vendor/acer/picasso/proprietary/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/acer/picasso/proprietary/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/acer/picasso/proprietary/libnvrm.so:system/lib/libnvrm.so \
    vendor/acer/picasso/proprietary/libnvsm.so:system/lib/libnvsm.so \
    vendor/acer/picasso/proprietary/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/acer/picasso/proprietary/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/acer/picasso/proprietary/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/acer/picasso/proprietary/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/acer/picasso/proprietary/Acer-AK00LB.kl:system/usr/keychars/Acer-AK00LB.kl \
    vendor/acer/picasso/proprietary/Acer-AK00LB.kcm:system/usr/keylayout/Acer-AK00LB.kcm \
    vendor/acer/picasso/proprietary/acer-dock.kl:system/usr/keylayout/acer-dock.kl \
    vendor/acer/picasso/proprietary/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \










